spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${S2_DB_HOST:localhost}:${S2_DB_PORT:5432}/${S2_DB_DATABASE:postgres}
    username: ${S2_DB_USER:postgres}
    password: ${S2_DB_PASSWORD:123456}
  sql:
    init:
      continue-on-error: true
      mode: always
      username: ${S2_DB_USER:postgres}
      password: ${S2_DB_PASSWORD:123456}
      schema-locations: classpath:db/schema-postgres.sql
      data-locations: classpath:db/data-postgres.sql
s2:
  embedding:
    store:
      provider: PGVECTOR
      base:
        url: ${S2_DB_HOST:127.0.0.1}
      port: ${S2_DB_PORT:5432}
      databaseName: ${S2_DB_DATABASE:postgres}
      user: ${S2_DB_USER:postgres}
      password: ${S2_DB_PASSWORD:123456}
      dimension: 512